/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_myapp_callyouself_AppString */

#ifndef _Included_com_myapp_callyouself_AppString
#define _Included_com_myapp_callyouself_AppString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_myapp_callyouself_AppString
 * Method:    userName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_myapp_callyouself_AppString_userName
  (JNIEnv *, jobject);

/*
 * Class:     com_myapp_callyouself_AppString
 * Method:    passWord
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_myapp_callyouself_AppString_passWord
  (JNIEnv *, jobject);

/*
 * Class:     com_myapp_callyouself_AppString
 * Method:    action
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_myapp_callyouself_AppString_action
  (JNIEnv *, jobject);

/*
 * Class:     com_myapp_callyouself_AppString
 * Method:    url
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_myapp_callyouself_AppString_url
  (JNIEnv *, jobject);

/*
 * Class:     com_myapp_callyouself_AppString
 * Method:    from
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_myapp_callyouself_AppString_from
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
