/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_myapp_jni_code_JNI */

#ifndef _Included_com_myapp_jni_code_JNI
#define _Included_com_myapp_jni_code_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_myapp_jni_code_JNI
 * Method:    helloFromCPP
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_myapp_jni_code_JNI_helloFromCPP
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
