/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_myapp_androidlinux_nativejni_NativeJni */

#ifndef _Included_com_myapp_androidlinux_nativejni_NativeJni
#define _Included_com_myapp_androidlinux_nativejni_NativeJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_myapp_androidlinux_nativejni_NativeJni
 * Method:    getLInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_myapp_androidlinux_nativejni_NativeJni_getLInt
  (JNIEnv *, jobject);

/*
 * Class:     com_myapp_androidlinux_nativejni_NativeJni
 * Method:    getLString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_myapp_androidlinux_nativejni_NativeJni_getLString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
